services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - mynetwork
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:latest
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
